# Import dependencies

In [1]:
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy
import os

# Test Environment

In [24]:
environment_name = 'CarRacing-v0'
env = gym.make(environment_name)

In [26]:
env.reset()

Track generation: 1187..1495 -> 308-tiles track


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [8]:
env.action_space

Box([-1.  0.  0.], [1. 1. 1.], (3,), float32)

In [9]:
env.observation_space


Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [10]:
# env.render()

True

# Testing Environment

In [18]:
episodes = 5
for episodes in range(1, episodes+1):
    obs = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state , reward, done, info = env.step(action)
        score += reward
    print("Episode:{} Score:{}".format(episodes, score))
env.close()

Track generation: 1151..1443 -> 292-tiles track
Episode:1 Score:-31.27147766323065
Track generation: 1019..1278 -> 259-tiles track
Episode:2 Score:-22.480620155038896
Track generation: 1275..1598 -> 323-tiles track
Episode:3 Score:-37.88819875776459
Track generation: 948..1193 -> 245-tiles track
Episode:4 Score:-18.032786885245862
Track generation: 1244..1559 -> 315-tiles track
Episode:5 Score:-36.30573248407704


# Train Model

In [22]:
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])

In [66]:
log_path = os.path.join('Training', 'Logs')


In [67]:
model = PPO("CnnPolicy", env, verbose=1, tensorboard_log=log_path)


Using cpu device
Wrapping the env in a VecTransposeImage.


In [68]:
model.learn(total_timesteps=5000000)

Track generation: 1012..1276 -> 264-tiles track
Logging to Training/Logs/PPO_3
Track generation: 1116..1407 -> 291-tiles track
Track generation: 1264..1584 -> 320-tiles track
-----------------------------
| time/              |      |
|    fps             | 125  |
|    iterations      | 1    |
|    time_elapsed    | 16   |
|    total_timesteps | 2048 |
-----------------------------
Track generation: 1286..1611 -> 325-tiles track
Track generation: 1111..1400 -> 289-tiles track
-----------------------------------------
| time/                   |             |
|    fps                  | 58          |
|    iterations           | 2           |
|    time_elapsed         | 69          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008219114 |
|    clip_fraction        | 0.0749      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.25       |
|    explained_variance   | 0.0115      |
|    learning_r

# Save Model

In [38]:
ppo_path = os.path.join('Training', 'Saved Models', 'PPO_2m_Driving_model_2')

In [39]:
model.load(ppo_path)

In [40]:
del model

In [41]:
model = PPO.load(ppo_path, env)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.


# Evaluate and Test

In [36]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)
#

/home/yogeshsoni/miniconda3/lib/python3.9/site-packages/stable_baselines3/common/evaluation.py:65: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


Track generation: 1112..1394 -> 282-tiles track
Track generation: 1163..1455 -> 292-tiles track


KeyboardInterrupt: 

In [37]:
env.close()

In [10]:
obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

Track generation: 1208..1521 -> 313-tiles track


ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().) 

In [11]:
env.close()

In [85]:
training_log_path = os.path.join(log_path, 'PPO_1')

In [86]:
training_log_path

'Training/Logs/PPO_1'

In [87]:
!tensorboard --logdir={training_log_path}

2022-11-07 11:56:13.164431: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/yogeshsoni/miniconda3/lib/python3.9/site-packages/cv2/../../lib64:
2022-11-07 11:56:13.164474: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-11-07 11:56:13.202030: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-07 11:56:14.002021: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/yogeshsoni/miniconda3/lib/python3.9/site-packages/cv2/../../lib64:
20